# Моделирование

Вероятность того, что после 9 подряд выпавших решек выпадет орёл, остаётся равной 1/2

In [384]:
import numpy as np
import pandas as pd
from numpy.random import binomial as bn, seed

In [406]:
seed(seed(seed(123)))
arr = bn(1, 0.5, size=1000000).astype(np.int)
arr.sum()

500072

In [420]:
seq = np.ones(20, dtype=np.int)
seq

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Расчёт

In [421]:
# Store sizes of input array and sequence
Na, Nseq = arr.size, seq.size

# Range of sequence
r_seq = np.arange(Nseq)
print(f"Na={Na}, Nseq={Nseq}, r_seq={r_seq}")

Na=1000000, Nseq=20, r_seq=[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [422]:
# Create 2D array of sliding indices across entire length of input array.
# Match up with the input sequence & get the matching starting indices.
M = (arr[np.arange(Na-Nseq+1)[:,None] + r_seq] == seq).all(1)

### Разбор

In [224]:
np.arange(Na-Nseq+1)[:,None] #+ r_seq

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17]])

In [228]:
np.arange(Na-Nseq+1)[:,None] + r_seq

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19]])

In [230]:
arr

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1])

In [234]:
arr[np.arange(Na-Nseq+1)[:,None] + r_seq]

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1]])

In [236]:
(arr[np.arange(Na-Nseq+1)[:,None] + r_seq]==seq).all(1)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False])

In [239]:
M

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False])

### Индексы

In [423]:
starting_indexes = np.where(M)[0]
starting_indexes

array([977628, 977629, 977630, 977631], dtype=int64)

In [424]:
ending_indexes = starting_indexes + Nseq + 1
ending_indexes

array([977649, 977650, 977651, 977652], dtype=int64)

In [425]:
arr[ending_indexes]

array([1, 1, 0, 0])

In [426]:
print(f"кол-во совпадений={len(arr[ending_indexes])}, кол-во орлов (1)={sum(arr[ending_indexes])}")

кол-во совпадений=4, кол-во орлов (1)=2


In [288]:
# Get the range of those indices as final output
#np.where(np.convolve(M, np.ones((Nseq), dtype=inWt))>0)[0]

### Функция

In [214]:
# def search_sequence_numpy(arr,seq):
""" Find sequence in an array using NumPy only.

Parameters
----------    
arr    : input 1D array
seq    : input 1D array

Output
------    
Output : 1D Array of indices in the input array that satisfy the 
matching of input sequence in the input array.
In case of no match, empty list is returned.
"""

' Find sequence in an array using NumPy only.\n\nParameters\n----------    \narr    : input 1D array\nseq    : input 1D array\n\nOutput\n------    \nOutput : 1D Array of indices in the input array that satisfy the \nmatching of input sequence in the input array.\nIn case of no match, empty list is returned.\n'